import { ProfessionalGuidanceCard } from "./professionalTypes";

export const PROFESSIONAL_GUIDANCE_CARDS: ProfessionalGuidanceCard[] = [
  {
    id: "cbt-fact-interpretation-separation",
    sourceTitle: "Beck Institute CBT case write-up example",
    sourceUrl: "https://beckinstitute.org/wp-content/uploads/2021/08/Case-Write-Up-Example.pdf",
    sourceKind: "case_formulation",
    topics: ["工作", "沟通", "自我评价", "关系"],
    cues: ["是不是", "被讨厌", "搞砸", "不行", "失败", "沉默"],
    principle: "把客观事件、自动解释、情绪和行为分开；解释是用户当下的想法，不等同于事实。",
    applyWhen: "用户把一个事件快速解释成别人讨厌自己、自己不行或事情全完了。",
    avoid: ["直接确认负面解释", "把一次事件写成长期人格结论", "马上给建议"],
    responseMove: "先承认这一下会让人不安，再轻轻区分“发生了什么”和“脑子里冒出的解释”。",
  },
  {
    id: "case-formulation-hypothesis-not-fact",
    sourceTitle: "Case Conceptualization in Clinical Practice and Training",
    sourceUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11303933/",
    sourceKind: "case_formulation",
    topics: ["家庭", "亲密关系", "自我评价", "长期模式"],
    cues: ["总是", "每次", "一看到", "又", "以前也", "不知道为什么"],
    principle: "个案概念化是随信息更新的假设；高层理解必须保留不确定性和反证。",
    applyWhen: "同一人物、主题或情绪多次出现，模型想形成长期理解时。",
    avoid: ["诊断", "创伤定性", "把关系模式说死", "忽略反证"],
    responseMove: "用“我不确定，但好像……”表达低置信假设，并给用户修正空间。",
  },
  {
    id: "helping-skills-before-advice",
    sourceTitle: "Towards Emotional Support Dialog Systems / ESConv",
    sourceUrl: "https://aclanthology.org/2021.acl-long.269/",
    sourceKind: "emotional_support",
    topics: ["倾诉", "压力", "低落", "焦虑", "关系"],
    cues: ["累", "烦", "撑不住", "难受", "崩", "不想说"],
    principle: "情感支持通常先使用承接、情绪反映和澄清；建议应该在用户准备好或主动请求时再出现。",
    applyWhen: "用户主要在表达痛苦、疲惫或混乱，而不是明确要求解决方案。",
    avoid: ["过早建议", "讲大道理", "连续追问", "机械复述"],
    responseMove: "先接住情绪重量，再给一个很小的表达入口。",
  },
  {
    id: "low-information-do-not-overread",
    sourceTitle: "Helping skills training vignettes",
    sourceUrl: "https://www.thenationalcouncil.org/resources/case-vignette-slides-and-sample-cases/",
    sourceKind: "helping_skills",
    topics: ["低信息", "沉默", "测试"],
    cues: ["1", "2", "嗯", "算了", "不知道", "随便", "q"],
    principle: "低信息表达不能被过度解释；它可能是测试、停顿、降低表达成本，也可能只是误触。",
    applyWhen: "用户只发数字、单字、表情式短句或撤回式表达。",
    avoid: ["猜测深层含义", "逼问原因", "把数字解释成分数", "连续问二选一"],
    responseMove: "允许不解释，给用户一个低压力继续或暂停的入口。",
  },
  {
    id: "recovery-counter-evidence",
    sourceTitle: "Psychology Tools case formulation overview",
    sourceUrl: "https://www.psychologytools.com/professional/techniques/case-conceptualization",
    sourceKind: "case_formulation",
    topics: ["恢复", "运动", "睡眠", "缓解", "反证"],
    cues: ["好一点", "缓过来", "跑步", "运动", "没那么", "恢复"],
    principle: "恢复线索是反证和资源，不只是附属信息；它应该削弱过于单一的压力源假设。",
    applyWhen: "用户提到同样压力仍在，但状态因某个行为或关系支持而改善。",
    avoid: ["继续只围绕压力源", "忽略改善", "把一次改善夸大成已经好了"],
    responseMove: "同时承认压力仍在和恢复线索出现，轻轻标记这个方法可能有用。",
  },
  {
    id: "crisis-switch-safety-mode",
    sourceTitle: "988 Lifeline warning signs",
    sourceUrl: "https://988lifeline.org/learn/warning-signs/",
    sourceKind: "safety",
    topics: ["危机", "自伤", "自杀", "安全"],
    cues: ["不想活", "轻生", "自杀", "伤害自己", "结束生命", "割腕"],
    principle: "出现自伤自杀风险时，系统必须优先安全，退出普通陪聊和长期理解模式。",
    applyWhen: "用户表达自杀、自伤、具体计划、无法保证安全或强烈绝望。",
    avoid: ["只说陪着你", "继续普通聊天", "承诺保密", "把危机当低落处理"],
    responseMove: "明确安全优先，鼓励联系身边可信的人、当地紧急服务或危机热线。",
  },
];
