import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";

import { assertComposerBehaviorStabilityEvidenceV1, createComposerBehaviorStabilityEvidenceV1 } from "../lib/composer-behavior-stability-evidence-authority";

const descriptor = {"version":"composer-behavior-stability-evidence-authority-v1-preaudit","owner":"lib/composer-behavior-stability-evidence-authority.ts#createComposerBehaviorStabilityEvidenceV1","trustedArtifact":{"path":"/private/tmp/composer-real-ledger-ingestion-v1.json","fileHash":"sha256:460832431491eb200f5c22d79b3cd74411e5233d1c81b3d7debc9cb0168dc22c","artifactHash":"sha256:389350baf9fa89a549a3567fc473dcd6569c0e5d91e3033aa0f2facdb64da904","ingestionDescriptorHash":"sha256:d80773b400cad630b02fed9d35cbacfd8bd762acbeafe57355d63e8541b1544d","ledgerAuthority":"composer_observation_ledger_authority_v1","sampleSetHash":"sha256:77044d3b25e4d504da97f641cd9bba62bdf7d0a292b6c6bfa5bbf880a657d73c","runConfigHash":"sha256:f58f72971ba6e1132914db84365754b66d97d0a5c55d9355ef1c430299e6e602"},"unit":{"includedOwnership":"ordinary","excludedOwnership":"safety","caseCount":12,"slots":[1,2,3],"observationsPerCase":3},"hardStableDefinition":{"allSlotsPresentExactlyOnce":true,"sameRunConfig":true,"invocationStatus":"success","notInvokedReason":null,"schemaValid":true,"turnBindingValid":true,"groundingRefsValid":true,"episodeRefValid":true,"eventRefValid":true,"isolationExactAndEqual":true,"outputHash":"sha256_nonnull","callsAllowed":[1,2],"repairRule":"reported_not_failure_if_final_strict_success"},"nonStabilityDimensions":["output_hash_equality","purpose_equality","reference_selection_equality","reply_length","segment_count","timings","token_values","created_at"],"result":{"status":["pass","fail"],"perCaseCountsOnly":true,"deepFrozen":true,"definitionHash":true,"inputArtifactHash":true,"resultHash":true,"humanGateUpgrade":false,"latencyGateUpgrade":false,"p1OverallUpgrade":false},"acceptanceIds":["A1:owner_exact","A2:no_caller_artifact_input","A3:fixed_path_exact","A4:file_hash_exact","A5:artifact_hash_exact","A6:ingestion_descriptor_exact","A7:artifact_root_exact","A8:artifact_canonical_hash_recomputed","A9:ledger_assert_exact","A10:ledger_hash_bound","A11:sample_set_hash_exact","A12:run_config_hash_exact","A13:38_rows_exact","A14:12_ordinary_cases_exact","A15:three_slots_exact_once","A16:safety_two_verified_excluded","A17:all_ordinary_success","A18:not_invoked_null","A19:five_strict_validity_true","A20:isolation_exact_equal","A21:output_hash_nonnull_sha256","A22:calls_one_or_two","A23:repair_reported_not_hard_failure","A24:output_hash_difference_allowed","A25:purpose_ref_difference_allowed_if_valid","A26:timing_token_date_excluded","A27:per_case_pass_fail","A28:overall_pass_iff_all_cases_pass","A29:result_exact_schema_hash_freeze","A30:tamper_recomputed_hash_reject","A31:no_plaintext_secret_output","A32:no_human_latency_p1_upgrade","A33:evaluator_unchanged","A34:no_qwen_production_db_write"]} as const;
assert.equal(createHash("sha256").update(JSON.stringify(descriptor)).digest("hex"), "52d57cdaf286aecab53b58a6251bcd0350ee6fd13dc43f58d99d2f7346b61dcb");
assert.equal(new Set(descriptor.acceptanceIds).size, 34);
const result = createComposerBehaviorStabilityEvidenceV1();
assertComposerBehaviorStabilityEvidenceV1(result);
assert.equal(result.overallStatus, "pass");
assert.equal(result.caseResults.length, 12);
assert(result.caseResults.every((item) => item.status === "pass" && item.observationCount === 3 && item.calls1 + item.calls2 === 3));
assert.equal(result.caseResults.filter((item) => item.distinctOutputCount > 1).length, 8, "output variation is reported, not failed");
assert.deepEqual(result.gateUpgrades, { behavior: "pass_or_fail_only", human: "unchanged_pending", latency: "unchanged_pending", budget: "unchanged_pending", p1Overall: "unchanged_pending" });
assert(Object.isFrozen(result) && Object.isFrozen(result.caseResults) && Object.isFrozen(result.caseResults[0]));
const forged = { ...structuredClone(result), caseResults: result.caseResults.map((item, index) => index === 0 ? { ...item, status: "fail" as const } : item), overallStatus: "fail" as const, resultHash: `sha256:${"0".repeat(64)}` };
assert.throws(() => assertComposerBehaviorStabilityEvidenceV1(forged), /behavior_result_binding/);
const serialized = JSON.stringify(result);
for (const forbidden of ['"reply":', '"currentUserText":', "QWEN_API_KEY", "DASHSCOPE_API_KEY", "dashscope.aliyuncs.com"]) assert(!serialized.includes(forbidden));
for (const path of ["lib/composer-p1-exit-evidence-evaluator.ts", "lib/composer-observation-ledger-authority.ts", "scripts/composer-shadow-qwen-local.ts"]) assert(!readFileSync(path, "utf8").includes("composer_behavior_stability_evidence_authority_v1"));
console.log(JSON.stringify({ status: "PASS", descriptorHash: result.definitionHash, behaviorStability: result.overallStatus, cases: result.caseResults.length, casesWithOutputVariation: result.caseResults.filter((item) => item.distinctOutputCount > 1).length, human: result.gateUpgrades.human, latency: result.gateUpgrades.latency, p1Overall: result.gateUpgrades.p1Overall }));
