import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { P6CacheKind, P6FixtureClaimKind, Prisma } from "@prisma/client";
import { prisma } from "../lib/prisma";
import {
  assertP6SnapshotEnvelope, deleteP6FixtureSourceLocally, readP6Cache,
  rebuildP6Cache, registerP6FrozenFixture, P6_RUNTIME_BOUNDARY,
} from "../services/growth/p6RelationshipGrowthCache";
import { P6_EXPECTED_IDS, P6_PRINCIPAL_TIME_IDS, P6_PRINCIPAL_TIME_REPAIR_IDS } from "./p6-relationship-growth-check";

const done = new Set<string>();
const integrityDone = new Set<string>();
const repairDone = new Set<string>();
const mark = (id: string, condition: unknown) => { assert(condition, id); done.add(id); };
const markIntegrity = (id: string, condition: unknown) => { assert(condition, id); integrityDone.add(id); };
const markRepair = (id: string, condition: unknown) => { assert(condition, id); repairDone.add(id); };
const envelopeFromRow = (row: Awaited<ReturnType<typeof registerP6FrozenFixture>>) => ({ userId: row.userId, descriptorId: row.descriptorId, sourceMemoryVersionId: row.sourceMemoryVersionId, sourceVersion: row.sourceVersion, authorityVersion: row.authorityVersion, projection: row.projection, claimKind: row.claimKind, dataClass: row.dataClass, content: row.content, accepted: row.accepted, isCurrent: row.isCurrent, artifactHash: row.artifactHash });

const main = async () => {
  const user = await prisma.user.create({ data: { nickname: "p6-fixture:tenant-a" } });
  const other = await prisma.user.create({ data: { nickname: "p6-fixture:tenant-b" } });
  try {
    const session = await prisma.session.create({ data: { userId: user.id, tokenHash: `p6-token-a-${user.id}`, expiresAt: new Date("2027-01-01T00:00:00.000Z") } });
    const otherSession = await prisma.session.create({ data: { userId: other.id, tokenHash: `p6-token-b-${other.id}`, expiresAt: new Date("2027-01-01T00:00:00.000Z") } });
    const auth = { sessionId: session.id, tokenHash: session.tokenHash };
    const otherAuth = { sessionId: otherSession.id, tokenHash: otherSession.tokenHash };
    const implementation = readFileSync(new URL("../services/growth/p6RelationshipGrowthCache.ts", import.meta.url), "utf8");
    markIntegrity("A1:factory_module_private", !/export\s+(?:const|function)\s+derivePrincipal/u.test(implementation));
    markIntegrity("A2:session_subject_stable", session.userId === user.id);
    await assert.rejects(readP6Cache({ auth: { sessionId: session.id, tokenHash: otherSession.tokenHash }, kind: P6CacheKind.RELATIONSHIP }));
    markIntegrity("A3:token_mismatch_reject", true);
    const expired = await prisma.session.create({ data: { userId: user.id, tokenHash: `expired-${user.id}`, expiresAt: new Date("2020-01-01T00:00:00.000Z") } });
    await assert.rejects(readP6Cache({ auth: { sessionId: expired.id, tokenHash: expired.tokenHash }, kind: P6CacheKind.RELATIONSHIP }));
    markIntegrity("A4:expired_session_reject", true);
    await assert.rejects(readP6Cache({ auth: { sessionId: expired.id, tokenHash: expired.tokenHash }, kind: P6CacheKind.RELATIONSHIP, now: new Date("1900-01-01T00:00:00.000Z") }));
    markRepair("RA1:backdated_eval_cannot_revive_expired", true);
    markRepair("RA2:production_auth_clock_not_caller_input", !/derivePrincipal\(auth,\s*now\)/u.test(implementation));
    await assert.rejects(registerP6FrozenFixture(auth, "unknown" as never));
    const now1 = new Date("2026-08-25T01:30:00.000Z");
    const beforeSemantic = await prisma.semanticMemory.count();
    const beforeChat = await prisma.chatMessage.count();
    const rel = await registerP6FrozenFixture(auth, "relationship_fact_v1");
    const relHyp = await registerP6FrozenFixture(auth, "relationship_hypothesis");
    await registerP6FrozenFixture(auth, "growth_fact");
    const cause = await registerP6FrozenFixture(auth, "causality_hypothesis");
    await registerP6FrozenFixture(auth, "safety");
    await registerP6FrozenFixture(auth, "secret");
    await registerP6FrozenFixture(auth, "credential");

    mark("S1:exact_schema:accepted", assertP6SnapshotEnvelope(envelopeFromRow(rel)));
    mark("S2:same_tenant:accepted", rel.userId === user.id);
    mark("S3:current_memory_version:accepted", rel.isCurrent);
    mark("S4:source_ids_exact:accepted", rel.sourceMemoryVersionId === "rel-source");
    mark("S5:source_versions_exact:accepted", rel.sourceVersion === 1);
    assert.throws(() => assertP6SnapshotEnvelope({ ...envelopeFromRow(rel), extra: true })); mark("S6:extra_key:reject", true);
    mark("S7:cross_tenant:reject", (await readP6Cache({ auth: otherAuth, kind: P6CacheKind.RELATIONSHIP })).status === "empty");
    markIntegrity("A5:cross_tenant_reject", (await readP6Cache({ auth: otherAuth, kind: P6CacheKind.RELATIONSHIP })).status === "empty");
    assert.throws(() => assertP6SnapshotEnvelope({ ...envelopeFromRow(rel), userId: other.id })); mark("S8:source_tenant_mismatch:reject", true);
    const relV2 = await registerP6FrozenFixture(auth, "relationship_fact_v2");
    mark("S9:superseded_memory:reject", !(await prisma.p6AcceptedMemorySnapshot.findUniqueOrThrow({ where: { id: rel.id } })).isCurrent && relV2.isCurrent);
    assert.throws(() => assertP6SnapshotEnvelope({ ...envelopeFromRow(relV2), sourceVersion: 0 })); mark("S10:unversioned:reject", true);
    assert.throws(() => assertP6SnapshotEnvelope({ ...envelopeFromRow(relV2), sourceMemoryVersionId: "" })); mark("S11:sourceless:reject", true);
    assert.throws(() => assertP6SnapshotEnvelope({ ...envelopeFromRow(relV2), content: "tampered" })); mark("S12:tampered_binding:reject", true);

    const relCache = await rebuildP6Cache({ auth, kind: P6CacheKind.RELATIONSHIP, cycle: "2026-08-25T01:00Z", now: now1 });
    const growthCache = await rebuildP6Cache({ auth, kind: P6CacheKind.GROWTH, cycle: "2026-08", now: now1 });
    const relTimePayload = relCache.payload as { generatedAt: string; staleAt: string; ttlMs: number; items: Array<{ snapshotCommitment: string }> };
    const growthTimePayload = growthCache.payload as { ttlMs: number };
    markIntegrity("T1:generated_not_future", relCache.generatedAt <= now1);
    markIntegrity("T2:relationship_ttl_frozen", relTimePayload.ttlMs === 3_600_000);
    markIntegrity("T3:growth_ttl_frozen", growthTimePayload.ttlMs === 86_400_000);
    markIntegrity("T4:stale_exact_generated_plus_ttl", relCache.staleAt.getTime() === relCache.generatedAt.getTime() + 3_600_000 && growthCache.staleAt.getTime() === growthCache.generatedAt.getTime() + 86_400_000);
    markIntegrity("T5:payload_db_time_exact", relTimePayload.generatedAt === relCache.generatedAt.toISOString() && relTimePayload.staleAt === relCache.staleAt.toISOString());
    markIntegrity("T6:commitment_hash_exact", /^hmac-sha256:[0-9a-f]{64}$/u.test(relCache.commitmentHash));
    markRepair("RC1:hmac_not_public_sha", relCache.commitmentHash.startsWith("hmac-sha256:"));
    markRepair("RC3:public_recompute_helper_absent", !/export\s+(?:const|function)\s+p6CacheCommitmentForAudit/u.test(implementation));
    const relArtifacts = await prisma.p6AcceptedMemorySnapshot.findMany({ where: { userId: user.id, projection: P6CacheKind.RELATIONSHIP, accepted: true, isCurrent: true, deletedAt: null }, orderBy: [{ sourceMemoryVersionId: "asc" }, { sourceVersion: "asc" }] });
    markIntegrity("T7:snapshot_commitment_exact", relTimePayload.items.every((item, index) => item.snapshotCommitment === relArtifacts[index].artifactHash));
    await prisma.p6RelationshipGrowthCache.update({ where: { id: relCache.id }, data: { staleAt: new Date(relCache.staleAt.getTime() + 1) } });
    markIntegrity("T8:time_tamper_empty", (await readP6Cache({ auth, kind: P6CacheKind.RELATIONSHIP, now: now1 })).status === "empty");
    const timeRestored = await rebuildP6Cache({ auth, kind: P6CacheKind.RELATIONSHIP, cycle: "2026-08-25T01:00Z", now: now1 });
    await prisma.p6RelationshipGrowthCache.update({ where: { id: timeRestored.id }, data: { commitmentHash: "sha256:tampered" } });
    markIntegrity("T9:payload_tamper_empty", (await readP6Cache({ auth, kind: P6CacheKind.RELATIONSHIP, now: now1 })).status === "empty");
    const coordinated = await rebuildP6Cache({ auth, kind: P6CacheKind.RELATIONSHIP, cycle: "2026-08-25T01:00Z", now: now1 });
    const coordinatedPayload = structuredClone(coordinated.payload) as Record<string, unknown>;
    const forgedGeneratedAt = new Date(now1.getTime() - 1_000);
    const forgedStaleAt = new Date(forgedGeneratedAt.getTime() + 3_600_000);
    coordinatedPayload.generatedAt = forgedGeneratedAt.toISOString();
    coordinatedPayload.staleAt = forgedStaleAt.toISOString();
    const oldPublicHash = `sha256:${createHash("sha256").update(JSON.stringify(coordinatedPayload)).digest("hex")}`;
    await prisma.p6RelationshipGrowthCache.update({ where: { id: coordinated.id }, data: { generatedAt: forgedGeneratedAt, staleAt: forgedStaleAt, payload: coordinatedPayload as Prisma.InputJsonValue, commitmentHash: oldPublicHash } });
    markRepair("RC2:coordinated_db_payload_time_tamper_empty", (await readP6Cache({ auth, kind: P6CacheKind.RELATIONSHIP, now: now1 })).status === "empty");
    await rebuildP6Cache({ auth, kind: P6CacheKind.RELATIONSHIP, cycle: "2026-08-25T01:00Z", now: now1 });
    const relPayload = relCache.payload as { items: Array<{ claimKind: string; sourceVersion: number }>; sourceMemoryVersionIds: string[]; authority: string };
    const growthPayload = growthCache.payload as { items: Array<{ claimKind: string }>; sourceMemoryVersionIds: string[] };
    mark("D1:safety_category:excluded", !growthPayload.sourceMemoryVersionIds.includes("safety"));
    mark("D2:secret_category:excluded", !relPayload.sourceMemoryVersionIds.includes("secret"));
    mark("D3:credential_category:excluded", !growthPayload.sourceMemoryVersionIds.includes("credential"));
    mark("D4:mixed_safe_and_safety:safety_zero", growthPayload.sourceMemoryVersionIds.includes("growth-source") && !growthPayload.sourceMemoryVersionIds.includes("safety"));
    mark("H1:explicit_user_fact:fact_allowed", relPayload.items.some((item) => item.claimKind === P6FixtureClaimKind.FACT));
    mark("H2:model_hypothesis:hypothesis_only", relPayload.items.some((item) => item.claimKind === P6FixtureClaimKind.HYPOTHESIS));
    mark("H3:unconfirmed_causality:hypothesis_only", growthPayload.items.some((item) => item.claimKind === P6FixtureClaimKind.HYPOTHESIS));
    mark("H4:inferred_relationship:hypothesis_only", relHyp.claimKind === P6FixtureClaimKind.HYPOTHESIS);
    const tamperRelationship = async (mutate: (payload: Record<string, unknown>) => void) => {
      const cache = await prisma.p6RelationshipGrowthCache.findUniqueOrThrow({ where: { userId_kind: { userId: user.id, kind: P6CacheKind.RELATIONSHIP } } });
      const payload = structuredClone(cache.payload) as Record<string, unknown>;
      mutate(payload);
      await prisma.p6RelationshipGrowthCache.update({ where: { id: cache.id }, data: { payload: payload as Prisma.InputJsonValue } });
      assert.equal((await readP6Cache({ auth, kind: P6CacheKind.RELATIONSHIP, now: now1 })).status, "empty");
      await rebuildP6Cache({ auth, kind: P6CacheKind.RELATIONSHIP, cycle: "2026-08-25T01:00Z", now: now1 });
    };
    await tamperRelationship((payload) => { (payload.items as Array<Record<string, unknown>>)[0].text = "recomputed tamper"; });
    await tamperRelationship((payload) => { (payload.items as unknown[]).pop(); });
    await tamperRelationship((payload) => { (payload.items as unknown[]).push(structuredClone((payload.items as unknown[])[0])); });
    await tamperRelationship((payload) => { (payload.items as unknown[]).reverse(); });
    await tamperRelationship((payload) => { (payload.items as Array<Record<string, unknown>>)[0].sourceVersion = 999; });
    await tamperRelationship((payload) => { (payload.items as Array<Record<string, unknown>>).find((item) => item.claimKind === "HYPOTHESIS")!.claimKind = "FACT"; });
    await tamperRelationship((payload) => { (payload.sourceMemoryVersionIds as string[]).push("growth-source"); });
    await tamperRelationship((payload) => { (payload.sourceMemoryVersionIds as string[]).push("secret"); });
    await prisma.p6AcceptedMemorySnapshot.update({ where: { id: cause.id }, data: { claimKind: P6FixtureClaimKind.FACT } });
    const repairedGrowth = await rebuildP6Cache({ auth, kind: P6CacheKind.GROWTH, cycle: "2026-08", now: now1 });
    mark("H5:hypothesis_to_fact:reject", !(repairedGrowth.payload as { sourceMemoryVersionIds: string[] }).sourceMemoryVersionIds.includes("cause-hyp"));

    mark("C1:relationship_current_projection:read", (await readP6Cache({ auth, kind: P6CacheKind.RELATIONSHIP, now: now1 })).status === "ready");
    mark("C2:growth_current_projection:read", (await readP6Cache({ auth, kind: P6CacheKind.GROWTH, now: now1 })).status === "ready");
    mark("C3:cache_version_and_source_ids:required", relCache.version === 1 && relCache.sourceMemoryVersionIds !== null);
    mark("C4:cache_only_write:required", await prisma.p6RelationshipGrowthCache.count({ where: { userId: user.id } }) === 2);
    mark("C5:memory_authority_write:zero", await prisma.semanticMemory.count() === beforeSemantic);
    mark("C6:conversation_authority_write:zero", await prisma.chatMessage.count() === beforeChat);
    mark("C7:prior_projection:not_current", repairedGrowth.version === 2 && await prisma.p6RelationshipGrowthCache.count({ where: { userId: user.id, kind: P6CacheKind.GROWTH } }) === 1);
    mark("C8:derived_output:non_authoritative", relPayload.authority === "derived_optional");

    mark("E1:cache_miss:empty", (await readP6Cache({ auth: otherAuth, kind: P6CacheKind.GROWTH })).status === "empty");
    mark("E2:stale_cache:empty", (await readP6Cache({ auth, kind: P6CacheKind.RELATIONSHIP, now: new Date(relCache.staleAt.getTime() + 1) })).status === "empty");
    await prisma.p6RelationshipGrowthCache.update({ where: { id: relCache.id }, data: { payload: { corrupt: true } } });
    mark("E3:corrupt_cache:empty", (await readP6Cache({ auth, kind: P6CacheKind.RELATIONSHIP, now: now1 })).status === "empty");
    mark("E4:timeout:empty", (await readP6Cache({ auth, kind: P6CacheKind.GROWTH, timeoutMs: 0 })).status === "empty");
    const now2 = new Date("2026-08-25T02:30:00.000Z");
    await rebuildP6Cache({ auth, kind: P6CacheKind.RELATIONSHIP, cycle: "2026-08-25T02:00Z", now: now2 });
    const growthBeforeDelete = await readP6Cache({ auth, kind: P6CacheKind.GROWTH, now: now2 });
    const relRequests = await deleteP6FixtureSourceLocally({ auth, sourceMemoryVersionId: "rel-source" });
    const growthAfterRelDelete = await readP6Cache({ auth, kind: P6CacheKind.GROWTH, now: now2 });
    mark("E5:deleted_source:empty", (await readP6Cache({ auth, kind: P6CacheKind.RELATIONSHIP, now: now2 })).status === "empty");
    await prisma.p6RelationshipGrowthCache.update({ where: { userId_kind: { userId: user.id, kind: P6CacheKind.GROWTH } }, data: { sourceMemoryVersionIds: ["unknown"] } });
    mark("E6:source_visibility_unknown:empty", (await readP6Cache({ auth, kind: P6CacheKind.GROWTH, now: now2 })).status === "empty");
    mark("E7:optional_failure:chat_unchanged", await prisma.chatMessage.count() === beforeChat);

    mark("R1:source_targeted:required", relRequests[0]?.sourceMemoryVersionId === "rel-source");
    mark("R2:relationship_marked:local", relRequests[0]?.kind === P6CacheKind.RELATIONSHIP);
    await rebuildP6Cache({ auth, kind: P6CacheKind.GROWTH, cycle: "2026-08", now: now2 });
    const growthRequests = await deleteP6FixtureSourceLocally({ auth, sourceMemoryVersionId: "growth-source" });
    mark("R3:growth_marked:local", growthRequests[0]?.kind === P6CacheKind.GROWTH);
    await deleteP6FixtureSourceLocally({ auth, sourceMemoryVersionId: "growth-source" });
    mark("R4:repeat_request:idempotent", await prisma.p6TargetedRecompute.count({ where: { userId: user.id, sourceMemoryVersionId: "growth-source" } }) === 1);
    mark("R5:unrelated_projection:unchanged", growthBeforeDelete.status === "ready" && growthAfterRelDelete.status === "ready");
    const rebuiltRel = await rebuildP6Cache({ auth, kind: P6CacheKind.RELATIONSHIP, cycle: "2026-08-25T03:00Z", now: new Date("2026-08-25T03:30:00.000Z") });
    mark("R6:rebuild_current_version:source_bound", rebuiltRel.version > 1 && !(rebuiltRel.sourceMemoryVersionIds as string[]).includes("rel-source"));

    mark("B1:production_integration:pending", P6_RUNTIME_BOUNDARY.productionIntegration === "pending");
    mark("B2:p4_runtime_integration:pending", P6_RUNTIME_BOUNDARY.p4RuntimeIntegration === "pending");
    mark("B3:p5_runtime_integration:pending", P6_RUNTIME_BOUNDARY.p5RuntimeIntegration === "pending");
    mark("B4:real_user_data:forbidden", P6_RUNTIME_BOUNDARY.dataSource === "local_frozen_fixture_only");
    mark("B5:real_provider_call:forbidden", P6_RUNTIME_BOUNDARY.providerCalls === 0);
    assert.deepEqual(done, P6_EXPECTED_IDS);
    assert.deepEqual(integrityDone, P6_PRINCIPAL_TIME_IDS);
    assert.deepEqual(repairDone, P6_PRINCIPAL_TIME_REPAIR_IDS);
    console.log(JSON.stringify({ status: "PASS", exactIdSet: [...done].sort(), integrityIdSet: [...integrityDone].sort(), repairIdSet: [...repairDone].sort() }));
  } finally { await prisma.user.deleteMany({ where: { id: { in: [user.id, other.id] } } }).catch(() => undefined); }
};
main().finally(() => prisma.$disconnect());
